[GLOBAL]
pants_version = "2.19.1"

pythonpath = ["%(buildroot)s/../pants-backends/pants-plugins/mdbook"]

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.lint.ruff",

  "pants.backend.tools.taplo",
  "pants.backend.experimental.adhoc",

  "pants_backend_mdbook",
]

[python]
interpreter_constraints = [">=3.10,<3.11"]
enable_resolves = true
default_resolve = "default"


[python-infer]
use_rust_parser = true
ambiguity_resolution = "by_source_root"

[python.resolves]
default = "locks/default.lock"
isort = "locks/tools/isort.lock"
ipython = "locks/tools/ipython.lock"
black = "locks/tools/black.lock"
docformatter = "locks/tools/docformatter.lock"

[python.resolves_to_interpreter_constraints]
black = [">=3.10,<3.11"]

[repl]
shell = "ipython"

[docformatter]
install_from_resolve = "docformatter"

[black]
install_from_resolve = "black"
interpreter_constraints = ["==3.10.*"]

[ipython]
install_from_resolve = "ipython"

[isort]
install_from_resolve = "isort"
args = '--resolve-all-configs'
interpreter_constraints = ["==3.10.*"]

[pytest]
install_from_resolve = "default"

[ruff]
args = ["--ignore", "E501"]
