name: Run CI

on:
  push:
    branches: [ "main" ]

  pull_request:

permissions:
  contents: read

jobs:
  test:

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache1-test-py3.10-pants-test
        named-caches-hash: ${{ hashFiles('locks/*.lock') }}

    - name: Test everything
      run: |
        pants test ::

  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        gha-cache-key: cache1-package-py3.10-pants-package
        named-caches-hash: ${{ hashFiles('locks/*.lock') }}

    - name: Package all targets
      run: |
        pants package ::

  check-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        gha-cache-key: cache1-package-py3.10-pants-lint
        named-caches-hash: ${{ hashFiles('locks/*.lock') }}

    - name: Run linters on all targets
      run: |
        pants update-build-files --check lint ::

  validate-tailor:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        gha-cache-key: cache1-package-py3.10-pants-lint
        named-caches-hash: ${{ hashFiles('locks/*.lock') }}

    - name: Validate that tailor files are up to date
      run: |
        pants tailor --check ::

  summarize:
    needs:
    - package
    - check-and-lint
    - validate-tailor
    - test

    runs-on: ubuntu-20.04
    if: success()

    outputs:
      success: ${{ steps.setoutput.outputs.success }}
    steps:
    - id: setoutput
      run: echo "success=true" >> $GITHUB_OUTPUT

  ci:
    runs-on: ubuntu-20.04
    if: always() # always run, so we never skip the check
    needs:
    - summarize
    steps:
    - run: |
        passed="${{needs.summarize.outputs.success}}"
        if [[ $passed == "true" ]]; then
          echo "CI succeeded"
          exit 0
        else
          echo "CI failed"
          exit 1
        fi
